// This file was autogenerated by aero-di. It is recommended to not change it
/* eslint-disable no-restricted-imports */
import { Logger as Logger_0 } from "./services/logger.service";
import { HTTPService as HTTPService_1 } from "./services/http.service";
import { ParentClass as ParentClass_2 } from "./pile-of-classes";
import { ChildClass as ChildClass_3 } from "./pile-of-classes";
import MyTestClass_4 from "./test";

export interface ParameterData {
  name: string;
  type: string;
}

export interface PropertyData {
  name: string;
  type: string;
  visibility: "public" | "protected" | "private";
}

export interface MethodData {
  name: string;
  parameters: ParameterData[];
  returnType: string;
  visibility: "public" | "protected" | "private";
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Constructor = new (...args: any[]) => any;
export interface ClassData {
  fqcn: string;
  name: string;
  ctor: Constructor | null;
  implementsInterfaces: string[];
  extendsClass: string | null;
  constructorParameters: ParameterData[];
  constructorVisibility: "public" | "protected" | "private";
  isAbstract: boolean;
  properties: PropertyData[];
  methods: MethodData[];
  isExported: boolean;
  exportMethod: "named" | "default";
}

export interface InterfaceData {
  fqin: string;
  name: string;
  properties: PropertyData[];
  extendsInterface: string | null;
  methods: MethodData[];
  isExported: boolean;
  exportMethod: "named" | "default";
}

export const classesReflection: ClassData[] = [
  {
    fqcn: "services/logger.service/Logger",
    name: "Logger",
    ctor: Logger_0,
    implementsInterfaces: [],
    extendsClass: null,
    constructorVisibility: "public",
    constructorParameters: [],
    isAbstract: false,
    properties: [],
    methods: [
      {
        name: "info",
        returnType: "void",
        parameters: [{ name: "...data", type: "unknown[]" }],
        visibility: "public",
      },
      {
        name: "panic",
        returnType: "void",
        parameters: [{ name: "...data", type: "unknown[]" }],
        visibility: "public",
      },
    ],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqcn: "services/http.service/HTTPService",
    name: "HTTPService",
    ctor: HTTPService_1,
    implementsInterfaces: [],
    extendsClass: null,
    constructorVisibility: "public",
    constructorParameters: [],
    isAbstract: false,
    properties: [],
    methods: [
      {
        name: "load",
        returnType: "Promise<T|undefined>",
        parameters: [
          { name: "path", type: "string" },
          {
            name: "options?",
            type: "{method:SendRequestMethod,body:Record<string,unknown>}",
          },
        ],
        visibility: "private",
      },
      {
        name: "send",
        returnType: "Promise<T|undefined>",
        parameters: [
          { name: "path", type: "string" },
          {
            name: "options?",
            type: "{method:SendRequestMethod,body:Record<string,unknown>}",
          },
        ],
        visibility: "public",
      },
    ],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqcn: "pile-of-classes/ParentClass",
    name: "ParentClass",
    ctor: ParentClass_2,
    implementsInterfaces: ["ParentInterface"],
    extendsClass: null,
    constructorVisibility: "public",
    constructorParameters: [],
    isAbstract: false,
    properties: [
      { name: "httpService", type: "HTTPService", visibility: "public" },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqcn: "pile-of-classes/ChildClass",
    name: "ChildClass",
    ctor: ChildClass_3,
    implementsInterfaces: [],
    extendsClass: "ParentClass",
    constructorVisibility: "public",
    constructorParameters: [],
    isAbstract: false,
    properties: [],
    methods: [
      {
        name: "spyOn",
        returnType: "Promise<void>",
        parameters: [{ name: "dude", type: "string='what1slove'" }],
        visibility: "public",
      },
    ],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqcn: "test/MyTestClass",
    name: "MyTestClass",
    ctor: MyTestClass_4,
    implementsInterfaces: [],
    extendsClass: null,
    constructorVisibility: "public",
    constructorParameters: [],
    isAbstract: false,
    properties: [],
    methods: [],
    isExported: true,
    exportMethod: "default",
  },
];

export const interfacesReflection: InterfaceData[] = [
  {
    fqin: "reflectionData/ParameterData",
    name: "ParameterData",
    extendsInterface: null,
    properties: [
      { name: "name", type: "string", visibility: "public" },
      { name: "type", type: "string", visibility: "public" },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqin: "reflectionData/PropertyData",
    name: "PropertyData",
    extendsInterface: null,
    properties: [
      { name: "name", type: "string", visibility: "public" },
      { name: "type", type: "string", visibility: "public" },
      {
        name: "visibility",
        type: '"public"|"protected"|"private"',
        visibility: "public",
      },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqin: "reflectionData/MethodData",
    name: "MethodData",
    extendsInterface: null,
    properties: [
      { name: "name", type: "string", visibility: "public" },
      { name: "parameters", type: "ParameterData[]", visibility: "public" },
      { name: "returnType", type: "string", visibility: "public" },
      {
        name: "visibility",
        type: '"public"|"protected"|"private"',
        visibility: "public",
      },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqin: "reflectionData/ClassData",
    name: "ClassData",
    extendsInterface: null,
    properties: [
      { name: "fqcn", type: "string", visibility: "public" },
      { name: "name", type: "string", visibility: "public" },
      { name: "ctor", type: "Constructor|null", visibility: "public" },
      { name: "implementsInterfaces", type: "string[]", visibility: "public" },
      { name: "extendsClass", type: "string|null", visibility: "public" },
      {
        name: "constructorParameters",
        type: "ParameterData[]",
        visibility: "public",
      },
      {
        name: "constructorVisibility",
        type: '"public"|"protected"|"private"',
        visibility: "public",
      },
      { name: "isAbstract", type: "boolean", visibility: "public" },
      { name: "properties", type: "PropertyData[]", visibility: "public" },
      { name: "methods", type: "MethodData[]", visibility: "public" },
      { name: "isExported", type: "boolean", visibility: "public" },
      { name: "exportMethod", type: '"named"|"default"', visibility: "public" },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
  {
    fqin: "reflectionData/InterfaceData",
    name: "InterfaceData",
    extendsInterface: null,
    properties: [
      { name: "fqin", type: "string", visibility: "public" },
      { name: "name", type: "string", visibility: "public" },
      { name: "properties", type: "PropertyData[]", visibility: "public" },
      { name: "extendsInterface", type: "string|null", visibility: "public" },
      { name: "methods", type: "MethodData[]", visibility: "public" },
      { name: "isExported", type: "boolean", visibility: "public" },
      { name: "exportMethod", type: '"named"|"default"', visibility: "public" },
    ],
    methods: [],
    isExported: true,
    exportMethod: "named",
  },
];
